services:
  DreggDVR-Beta:
    image: dreggdvr-beta:latest
    build:
      context: .
    container_name: DreggDVR-Beta
    command: python /_Dregg_DVR/main.py --ui
    ports:
      - "8501:8501"
    volumes:
      - D:\GitHub\DregDVR:/_Dregg_DVR:ro
      - D:\Containers\Mounts\Dreggs\Beta\_DVR_Runtime:/_DVR_Runtime
      - D:\Containers\Mounts\Dreggs\Beta\_DVR_Data:/_DVR_Data
