services:
  DreggDVR-Beta:
    image: mcr.microsoft.com/playwright/python:v1.58.0-noble
    container_name: DreggDVR-Beta
    command: python /_Dregg_DVR/main.py
    volumes:
      - D:\GitHub\DregDVR:/_Dregg_DVR:ro
      - D:\Containers\Mounts\Dreggs\Beta\_DVR_Runtime:/_DVR_Runtime
      - D:\Containers\Mounts\Dreggs\Beta\_DVR_Data:/_DVR_Data
